### ISSUE TITLE
支付时显示failed to request payment gateway: 服务器返回非正常HTTP状态500

### ISSUE THREAD

**Issue by liuyuhang9066** [essesoul/Cloudreve-AfdianPay#8]
[2023-10-13 00:55:52,852] ERROR in app: Exception on /order/create [POST]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloudreve-AfdianPay-master\src\cloudreve_pay.py", line 63, in order
    if os.environ.get('SITE_URL')[-1] == "/":
       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
***.***.***.*** - - [2023-10-13 00:55:52] "POST /order/create HTTP/1.1" 500 401 0.125055

**Comment by essesoul** [comment]
检查一下`.enc`文件是否填写正确

**Comment by liuyuhang9066** [comment]
我检查了好多遍.env文件，并没有写错

**Comment by essesoul** [comment]
> if os.environ.get('SITE_URL')[-1] == "/":
> \~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
> TypeError: 'NoneType' object is not subscriptable

说明.env里的“SITE_URL”没有读取成功，检查一下依赖项
